# Development-specific overrides
server:
  debug: true
  port: 8001

logging:
  level: "DEBUG"
  console_output: true
  
development:
  auto_reload: true
  profiling_enabled: true
  debug_knowledge_engine: true
  
cache:
  directory: "./cache/dev"
  
knowledge_sources:
  cycling74_docs:
    cache_duration: 600  # 10 minutes for faster development
    
  minutiae_repo:
    update_interval: 60  # 1 minute for faster updates